/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.doctor_chaneling_center.view;

import static edu.ijse.doctor_chaneling_center.view.Reception_DashBoard.lblDateMain;
import static edu.ijse.doctor_chaneling_center.view.Reception_DashBoard.lblTimeMain;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.UIManager;

/**
 *
 * @author USER
 */
public class Addmin_DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form Addmin_DashBoard
     */
    public Addmin_DashBoard() {
        initComponents();
        setDate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCreateDoctorShedule = new javax.swing.JButton();
        btnAddDoctor = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlLoad = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTimeMain = new javax.swing.JLabel();
        lblDateMain = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateDoctorShedule.setBackground(new java.awt.Color(204, 255, 255));
        btnCreateDoctorShedule.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnCreateDoctorShedule.setForeground(new java.awt.Color(51, 51, 51));
        btnCreateDoctorShedule.setText("CREATE DOCTOR SHEDULE");
        btnCreateDoctorShedule.setOpaque(false);
        btnCreateDoctorShedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorSheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateDoctorShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 310, -1));

        btnAddDoctor.setBackground(new java.awt.Color(204, 255, 255));
        btnAddDoctor.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnAddDoctor.setForeground(new java.awt.Color(51, 51, 51));
        btnAddDoctor.setText("LOG OUT");
        btnAddDoctor.setOpaque(false);
        btnAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 310, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("ADD DOCTOR SPACIALITY");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1070, -1));

        pnlLoad.setBackground(new java.awt.Color(0, 153, 153));
        pnlLoad.setMinimumSize(new java.awt.Dimension(1340, 640));
        pnlLoad.setPreferredSize(new java.awt.Dimension(1340, 640));
        jPanel1.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1340, 630));
        pnlLoad.getAccessibleContext().setAccessibleParent(pnlLoad);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ASIRI CHANELLING CENTER");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOSPITAL ROAD , MATARA. 041-2234455 / 041-2234456");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 370, 20));

        lblTimeMain.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lblTimeMain.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimeMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(lblTimeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 210, 50));

        lblDateMain.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lblDateMain.setForeground(new java.awt.Color(255, 255, 255));
        lblDateMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(lblDateMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 310, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/doctor_chaneling_center/view/received_1388260121256265.jpeg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDoctorSheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorSheduleActionPerformed
        CreateDoctorShedule cds = new CreateDoctorShedule();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        cds.setSize(pnlLoad.getSize());
        pnlLoad.add(cds);
        cds.setVisible(true);
    }//GEN-LAST:event_btnCreateDoctorSheduleActionPerformed

    private void btnAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoctorActionPerformed
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddDoctorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Speciality ad=new Speciality();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        ad.setSize(pnlLoad.getSize());
        pnlLoad.add(ad);
        ad.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
//            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                
//                if ("Window".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }*/
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmin_DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDoctor;
    private javax.swing.JButton btnCreateDoctorShedule;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblDateMain;
    public static javax.swing.JLabel lblTimeMain;
    private javax.swing.JPanel pnlLoad;
    // End of variables declaration//GEN-END:variables

private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d1);
        lblDateMain.setText(formateDate);
    }

    private void setTime() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
        String formateDate = df.format(d1);
        lblTimeMain.setText(formateDate);
    }
    
}
