/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.doctor_chaneling_center.view;

//import edu.ijse.doctor_chaneling_center.model.Patient;
import java.awt.Color;
import java.awt.Component;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import static java.awt.SystemColor.MENU;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author USER
 */
public class Reception_DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form Reception_DashBoard
     */
    public Reception_DashBoard() {
        initComponents();
        setDate();
        setTime();
        /*KeyboardFocusManager kfm=KeyboardFocusManager.getCurrentKeyboardFocusManager();
         kfm.addKeyEventPostProcessor(new KeyEventPostProcessor() {

         @Override
         public boolean postProcessKeyEvent(KeyEvent e) {
         if(e.getID()==KeyEvent.KEY_PRESSED){
         switch(e.getKeyCode()){
         case KeyEvent.VK_F1:
         navigateMe(MENU.SEARCHDOCTORSHEDULE);
         break;
         case KeyEvent.VK_F2:
         nevigateMe(MENU.SEARCHAPPOINTMENT);
         break;
         case KeyEvent.VK_F3:
         nevigateMe(MENU.ADDPATIENT);
         break;
         case KeyEvent.VK_F4:
         nevigateMe(MENU.ADDAPPOINTMENT);
         break;
         case KeyEvent.VK_F5:
         nevigateMe(MENU.PAYMENT);
         break;
                                
         }
         }
         return true;
         }
            
         });*/

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                JButton btn = (JButton) component;
                if (btn.getName() != null && btn.getName().equals("Menu")) {
                    btn.addMouseListener(new MouseAdapter() {

                        public void mouseEntered(MouseEvent e) {
                            btn.setBackground(Color.red);
                            super.mouseEntered(e);
                        }
                    });
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLoad = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAnimation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDateMain = new javax.swing.JLabel();
        lblTimeMain = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoad.setBackground(new java.awt.Color(255, 255, 204));
        pnlLoad.setMinimumSize(new java.awt.Dimension(1140, 640));
        pnlLoad.setPreferredSize(new java.awt.Dimension(1140, 640));
        pnlLoad.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 1150, 610));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 153));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH DOCTOR SHEDULE");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 51), null, null));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 60));

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH APPOINTMENT");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 51), null, null));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 70));

        jLabel7.setBackground(new java.awt.Color(51, 0, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOG OUT");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 51), null, null));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 200, 60));

        jLabel5.setBackground(new java.awt.Color(51, 0, 153));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADD APPOINTMENT");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 51), null, null));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 60));

        jLabel8.setBackground(new java.awt.Color(51, 0, 153));
        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEARCH PATIENT APPOINTMENT");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 51), null, null));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 620));

        jPanel3.setBackground(new java.awt.Color(51, 0, 153));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnimation.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblAnimation.setForeground(new java.awt.Color(204, 255, 204));
        lblAnimation.setText("ASIRI CHANELLING CENTER");
        jPanel3.add(lblAnimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 343, 50));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("HOSPITAL ROAD , MATARA. 041-2234455 / 041-2234456");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 373, -1));

        lblDateMain.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        lblDateMain.setForeground(new java.awt.Color(255, 255, 255));
        lblDateMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(lblDateMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 250, 60));

        lblTimeMain.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        lblTimeMain.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimeMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(lblTimeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 270, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/doctor_chaneling_center/view/received_1388260121256265.jpeg"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 760));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        SearchDoctorShedule sds = new SearchDoctorShedule();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        sds.setSize(pnlLoad.getSize());
        pnlLoad.add(sds);
        sds.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        AddAppointment1 aa = new AddAppointment1();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        aa.setSize(pnlLoad.getSize());
        pnlLoad.add(aa);
        aa.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        SearchAppointment searchAppointment = new SearchAppointment();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        searchAppointment.setSize(pnlLoad.getSize());
        pnlLoad.add(searchAppointment);
        searchAppointment.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        SearchPatientAppointment searchPatientAppointment = new SearchPatientAppointment();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        searchPatientAppointment.setSize(pnlLoad.getSize());
        pnlLoad.add(searchPatientAppointment);
        searchPatientAppointment.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reception_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reception_DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAnimation;
    public static javax.swing.JLabel lblDateMain;
    private javax.swing.JLabel lblImage;
    public static javax.swing.JLabel lblTimeMain;
    public static javax.swing.JPanel pnlLoad;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d1);
        lblDateMain.setText(formateDate);
    }

    private void setTime() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
        String formateDate = df.format(d1);
        lblTimeMain.setText(formateDate);
    }

}
